module.exports = [
    {
          name: 'iPhone 14 Pro Max',
          price: 1200,
          model: '14 Pro Max',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-pro-max-colors.png']
      },
    {
          name: 'iPhone 14 Pro',
          price: 1100,
          model: '14 Pro',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-pro-colors.png']
      },
    {
          name: 'iPhone 14 Plus',
          price: 1100,
          model: '14 Plus',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Optical Image Stabilization, 4K Video Recording, Accelerometer, Barometer, Bluetooth Enabled, Digital Compass, Dual Front Camera.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-plus-colors.png']
      },
    {
          name: 'iPhone 14',
          price: 1000,
          model: '14',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-colors.png']
      },
    {
          name: 'iPhone SE (3rd generation)',
          price: 950,
          model: 'SE (3rd generation)',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-se-3rd-gen-colors.png']
      },
    {
          name: 'iPhone 13 Pro Max',
          price: 900,
          model: '13 Pro Max',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Optical Image Stabilization, 4K Video Recording, Accelerometer, Barometer, Bluetooth Enabled, Digital Compass, Dual Front Camera.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/2022-spring-iphone13-pro-max-colors.png']
      },
    {
          name: 'iPhone 13 Pro',
          price: 850,
          model: '13 Pro',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/2022-spring-iphone13-pro-colors.png']
      },
    {
          name: 'iPhone 13',
          price: 800,
          model: '13',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/2022-spring-iphone13-colors.png']
      },
    {
          name: 'iPhone 13 mini',
          price: 850,
          model: '13 mini',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/2022-iphone13-mini-colors.png']
      },
    {
          name: 'iPhone 12 Pro Max',
          price: 750,
          model: '12 Pro Max',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone12promax/iphone12-pro-max-colors.jpg']
      },
    {
          name: 'iPhone 12 Pro',
          price: 750,
          model: '12 Pro',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone12pro/iphone12-pro-colors.jpg']
      },
    {
          name: 'iPhone 12',
          price: 750,
          model: '12',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Optical Image Stabilization, 4K Video Recording, Accelerometer, Barometer, Bluetooth Enabled, Digital Compass, Dual Front Camera.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/2021-iphone12-colors.png'],
          discount:'20'
      },
    {
          name: 'iPhone 12 mini',
          price: 750,
          model: '12 mini',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/2021-iphone12-mini-colors.png'],
          discount:'25'
      },
    {
          name: 'iPhone SE (2nd generation)',
          price: 700,
          model: 'SE (2nd generation)',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone_se/iphone-se-2nd-gen-colors.jpg']
      },
    {
          name: 'iPhone 11 Pro',
          price: 700,
          model: '11 Pro',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Optical Image Stabilization, 4K Video Recording, Accelerometer, Barometer, Bluetooth Enabled, Digital Compass, Dual Front Camera.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/identify-iphone-11pro.jpg']
      },
    {
          name: 'iPhone 11 Pro Max',
          price: 700,
          model: '11 Pro Max',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/identify-iphone-11pro-max.jpg'
        ],
        discount:'10'
      },
    {
          name: 'iPhone 11',
          price: 650,
          model: '11',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/identify-iphone-11-colors.jpg']
      },
    {
          name: 'iPhone XS',
          price: 600,
          model: 'XS',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Optical Image Stabilization, 4K Video Recording, Accelerometer, Barometer, Bluetooth Enabled, Digital Compass, Dual Front Camera.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-xs-colors.jpg']
      },
    {
          name: 'iPhone XS Max',
          price: 600,
          model: 'XS Max',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: '3D Depth Camera, 3D Depth Sensor, 3D Face Recognition, 4K Video Recording, Accelerometer, Ambient Light Sensor.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-xs-max-colors.jpg']
      },
    {
          name: 'iPhone XR',
          price: 600,
          model: 'XR',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Optical Image Stabilization, 4K Video Recording, Accelerometer, Barometer, Bluetooth Enabled, Digital Compass, Dual Front Camera.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-xr/identify-iphone-xr-colors.jpg']
      },
    {
          name: 'iPhone X',
          price: 650,
          model: 'X',
          type: 'smartphones',
          stock: 13,
          camera: '10Mpx',
          processor: 'OctaCore',
          description: 'Super Retina Xdr Display, Fast Wireless Charging, Dust-Resistant, OLED Display, Telephoto Lens, Water-Resistant, 4K Video Recording.',
          img: ['https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-x-colors.jpg']
      },
  
  ]