module.exports = [
    { email: 'prueba01@henrygadget.com', code: 101, confirm: true },
    { email: 'prueba02@henrygadget.com', code: 102, confirm: true },
    { email: 'prueba03@henrygadget.com', code: 103, confirm: true },
    { email: 'prueba04@henrygadget.com', code: 104, confirm: true },
    { email: 'prueba05@henrygadget.com', code: 105, confirm: false },
    { email: 'prueba06@henrygadget.com', code: 106, confirm: false },
    { email: 'prueba07@henrygadget.com', code: 107, confirm: true },
    { email: 'prueba08@henrygadget.com', code: 108, confirm: true },
    { email: 'prueba09@henrygadget.com', code: 109, confirm: true },
    { email: 'prueba10@henrygadget.com', code: 110, confirm: true },
    { email: 'prueba11@henrygadget.com', code: 111, confirm: false },
    { email: 'prueba12@henrygadget.com', code: 112, confirm: true },
    { email: 'prueba13@henrygadget.com', code: 113, confirm: true },
    { email: 'prueba14@henrygadget.com', code: 114, confirm: true },
    { email: 'prueba15@henrygadget.com', code: 115, confirm: true },
    { email: 'prueba16@henrygadget.com', code: 116, confirm: false },
    { email: 'prueba17@henrygadget.com', code: 117, confirm: true },
    { email: 'prueba18@henrygadget.com', code: 118, confirm: true },
    { email: 'prueba19@henrygadget.com', code: 119, confirm: false },
    { email: 'prueba20@henrygadget.com', code: 120, confirm: true },
];